### ISSUE TITLE
Unknown host repository-estatio.forge.cloudbees.com - Apache isis

### ISSUE THREAD

**Issue by sathiya-dev** [isisaddons/isis-app-todoapp#13]
I have been using apache isis for creatign webservices. Today, when I tried to deploy a webservice developed using apache isis in my machine I am facing the below issue

 

**_Could not resolve dependencies for project com.abc:section-mapper-webapp:war:1.0-SNAPSHOT: Failed to collect dependencies at org.isisaddons.module.togglz:isis-module-togglz-glue:jar:1.13.0 -> org.isisaddons.module.settings:isis-module-settings-dom:jar:1.13.0-SNAPSHOT: Failed to read artifact descriptor for org.isisaddons.module.settings:isis-module-settings-dom:jar:1.13.0-SNAPSHOT: Could not transfer artifact org.isisaddons.module.settings:isis-module-settings-dom:pom:1.13.0-SNAPSHOT from/to Cloudbees snapshots (http://repository-estatio.forge.cloudbees.com/snapshot/): repository-estatio.forge.cloudbees.com: Unknown host repository-estatio.forge.cloudbees.com_**

The repository seems to have been moved. I checked for an alternate repository to use togglz and I couldn't find any other. Can someone please help me in resolving this issue as I am running on a tight schedule. Any help would be much appreciated. Cheers!

**Comment by rydnr** [comment]
I got the same issue. It seems togglz's 0.13.0 pom points to a SNAPSHOT version of isis-module-settings-dom.jar. I changed pom.xml's isis.module.togglz.version to 1.12.0 and the build finishes correctly.
I'm not sure if it will work fine at runtime.

**Comment by rydnr** [comment]
It fails with
```
Caused by: java.lang.NoSuchMethodError: org.apache.isis.core.runtime.system.context.IsisContext.doInSession(Ljava/util/concurrent/Callable;)Ljava/lang/Object;
        at org.isisaddons.module.togglz.glue.spi.StateRepositoryUsingApplicationSettingsWithGson.getFeatureState(StateRepositoryUsingApplicationSettingsWithGson.java:27)
        at org.togglz.core.manager.DefaultFeatureManager.isActive(DefaultFeatureManager.java:67)
        at todoapp.dom.ToDoAppFeature.isActive(ToDoAppFeature.java:17)
        at todoapp.dom.todoitem.ToDoItemRepository.getToDoItemRepositoryImpl(ToDoItemRepository.java:41)
        at todoapp.dom.todoitem.ToDoItemRepository.lambda$findByAtPathAndComplete$1(ToDoItemRepository.java:59)
        at org.apache.isis.applib.services.queryresultscache.QueryResultsCache.execute(QueryResultsCache.java:152)
        at org.apache.isis.applib.services.queryresultscache.QueryResultsCache.execute(QueryResultsCache.java:138)
```

I just fixed my `~/.m2/repository/org/isisaddons/module/togglz/isis-module-togglz-glue/1.13.0/isis-module-togglz-glue-1.13.0.pom` so that `isis-module-settings.version` and `isis-module-security.version` both point to *1.13.0*.

**Comment by maestros** [comment]
Is this project still active? I am also hitting the same issue here.

**Comment by danhaywood** [comment]
This particular repo isn't being maintained, though the Apache Isis
framework itself is still very much active.

**Comment by maestros** [comment]
Ah, got it! Many thanks @danhaywood!
